spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.url=jdbc:postgresql://dpg-d778t7fkijhs73e483lg-a.frankfurt-postgres.render.com/test_render_279q
spring.datasource.username=test_render_279q_user
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=e7X57qWhLhSMgpHi1WTUMa9ar2xhNkaa
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator